apiVersion: v1
kind: Namespace
metadata:
  name: password-generator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator
  namespace: password-generator
spec:
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
      - name: password-generator
        image: abdofarag/password-generator:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
